/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Distributor;

import UI.CDC.*;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Organization.OrganizationDirectory;
import java.awt.Image;
import java.nio.file.Paths;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bhargavi
 */
public class ManageEmployee extends javax.swing.JPanel {

    /**
     * Creates new form ManageCdcEmployee
     */
    Enterprise enterprise;
    private OrganizationDirectory directory;
    JPanel workArea;
    private static final String AFILENAME = Paths.get("src").toAbsolutePath().toString();// path to the data store
    private String aimagePath = AFILENAME+"/Images/manage_employee.png";
    public ManageEmployee(OrganizationDirectory directory,JPanel workArea) {
        initComponents();
        this.directory = directory;
        this.workArea = workArea;
         ImageIcon aimgIcon = new ImageIcon(aimagePath);
        Image aI = aimgIcon.getImage();
        Image aDimg = aI.getScaledInstance(90, 90,Image.SCALE_SMOOTH);
        ImageIcon aImgThisImg = new ImageIcon(aDimg);
        lblI.setIcon(aImgThisImg);
        
        
        populateOrganizationComboBox();
        populateOrganizationEmpComboBox();
    }
    
    
      public void populateOrganizationComboBox(){
        cbFilterOrg.removeAllItems();
        
        for (Organization organization : directory.getOrganizationList()){
            cbFilterOrg.addItem(organization);
        }
    }
    
    public void populateOrganizationEmpComboBox(){
        cbOrg.removeAllItems();
        
        for (Organization organization : directory.getOrganizationList()){
            cbOrg.addItem(organization);
        }
    }
    
    
    private void populateTable(Organization organization){
        DefaultTableModel model = (DefaultTableModel) tblOrg.getModel();
        
        model.setRowCount(0);
        
        for (Employee employee : organization.getEmployeeDirectory().getEmployeeList()){
            Object[] row = new Object[1];            
            row[0] = employee;
            model.addRow(row);
        }
    }
    
     private void organizationJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        Organization organization = (Organization) cbFilterOrg.getSelectedItem();
        if (organization != null){
            populateTable(organization);
        }
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbFilterOrg = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrg = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbOrg = new javax.swing.JComboBox();
        txtName = new javax.swing.JTextField();
        btnCreate = new javax.swing.JButton();
        lblI = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 156, 141));
        jLabel1.setText("Manage Employee");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 34, -1, -1));

        jLabel2.setText("Filter by Organization");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 112, -1, -1));

        cbFilterOrg.setBackground(new java.awt.Color(255, 156, 141));
        cbFilterOrg.setForeground(new java.awt.Color(255, 255, 255));
        cbFilterOrg.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbFilterOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFilterOrgActionPerformed(evt);
            }
        });
        add(cbFilterOrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 109, 147, -1));

        tblOrg.setBackground(new java.awt.Color(255, 156, 141));
        tblOrg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Name"
            }
        ));
        jScrollPane1.setViewportView(tblOrg);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 383, 143));

        jLabel3.setText("Organization :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 328, -1, -1));

        jLabel4.setText("Name :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 373, -1, -1));

        cbOrg.setBackground(new java.awt.Color(255, 156, 141));
        cbOrg.setForeground(new java.awt.Color(255, 255, 255));
        cbOrg.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cbOrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 325, 137, -1));
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 370, 137, -1));

        btnCreate.setBackground(new java.awt.Color(255, 156, 141));
        btnCreate.setForeground(new java.awt.Color(255, 255, 255));
        btnCreate.setText("Create Employee");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 435, 160, 30));
        add(lblI, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 530, 150, 130));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        
        if (txtName.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Name cannot be empty");
        } else {
            Organization organization = (Organization) cbOrg.getSelectedItem();
            String name = txtName.getText();
            organization.getEmployeeDirectory().createEmployee(name);
            populateTable(organization);
            txtName.setText("");
              JOptionPane.showMessageDialog(null, "Employee added!.", "Dialogue", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnCreateActionPerformed

    private void cbFilterOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFilterOrgActionPerformed
        // TODO add your handling code here:
        Organization organization = (Organization) cbFilterOrg.getSelectedItem();
        if (organization != null){
            populateTable(organization);
        }
    }//GEN-LAST:event_cbFilterOrgActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JComboBox cbFilterOrg;
    private javax.swing.JComboBox cbOrg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblI;
    private javax.swing.JTable tblOrg;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
