/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.PHD;

import Business.Enterprise.Enterprise;
import Business.Enterprise.HospitalEnterprise;
import Business.Enterprise.PHDEnterprise;
import Business.Network.Network;
import Business.WorkQueue.PHDHospitalApproval;
import java.awt.Color;
import java.awt.Image;
import java.nio.file.Paths;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author bhargavi
 */
public class ApproveHospital extends javax.swing.JPanel {

    /**
     * Creates new form ApproveHospital
     */
//    public ApproveHospital() {
//        initComponents();
//    }
    
    private JPanel workArea;
    private PHDEnterprise phde;
    private Network network;

    private static final String logoFILENAME = Paths.get("src").toAbsolutePath().toString();// path to the data store
    private String logoImagePath = logoFILENAME+"/Images/approve_hosp.png";
    
    public ApproveHospital(PHDEnterprise phde, Network network, JPanel workArea) {
        initComponents();
        this.workArea = workArea;
        this.phde = phde;
        this.network = network;
        populateHospitalTable();
        lblApprove.setEnabled(false);
        lblPending.setEnabled(false);
        lblTotal.setEnabled(false);
//        btnApprove.setEnabled(false);

ImageIcon logoimgIcon = new ImageIcon(logoImagePath);
        Image lI = logoimgIcon.getImage();
        Image logoDimg = lI.getScaledInstance(90, 90,Image.SCALE_SMOOTH);
        ImageIcon logoImgThisImg = new ImageIcon(logoDimg);
        jLabel5.setIcon(logoImgThisImg);

        
    }

    private void populateHospitalTable() {
        DefaultTableModel dtm = (DefaultTableModel) tblHos.getModel();
        dtm.setRowCount(0);
        for (PHDHospitalApproval hospitalApproval : phde.getHospitalApprovalList()) {
            Object[] row = new Object[4];
            row[0] = hospitalApproval;
            row[1] = hospitalApproval.getHospitalEnterprise();
            row[2] = hospitalApproval.getHospitalStatus();
            row[3] = hospitalApproval.getHospitalEnterprise().isHospitalApproved();
            dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHos = new javax.swing.JTable();
        btnSummary = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblApprove = new javax.swing.JTextField();
        btnApprove = new javax.swing.JButton();
        lblTotal = new javax.swing.JTextField();
        lblPending = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1100, 800));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 156, 141));
        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setText("Hospital Approval");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 45, -1, -1));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

        tblHos.setBackground(new java.awt.Color(255, 156, 141));
        tblHos.setForeground(new java.awt.Color(255, 255, 255));
        tblHos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Hospital Name", "PHD Status", "Approval status"
            }
        ));
        jScrollPane1.setViewportView(tblHos);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 94, 685, 191));

        btnSummary.setBackground(new java.awt.Color(255, 156, 141));
        btnSummary.setForeground(new java.awt.Color(255, 255, 255));
        btnSummary.setText("Total Requests Summary");
        btnSummary.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSummary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSummaryActionPerformed(evt);
            }
        });
        add(btnSummary, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 536, -1, 32));

        jLabel2.setText("Approved :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 366, -1, -1));

        jLabel3.setText("Pending for Approval :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 421, -1, -1));

        jLabel4.setText("Total :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(417, 476, -1, -1));
        add(lblApprove, new org.netbeans.lib.awtextra.AbsoluteConstraints(499, 360, 108, -1));

        btnApprove.setBackground(new java.awt.Color(255, 156, 141));
        btnApprove.setForeground(new java.awt.Color(255, 255, 255));
        btnApprove.setText("Approve");
        btnApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveActionPerformed(evt);
            }
        });
        add(btnApprove, new org.netbeans.lib.awtextra.AbsoluteConstraints(736, 297, -1, -1));
        add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(499, 470, 108, -1));
        add(lblPending, new org.netbeans.lib.awtextra.AbsoluteConstraints(499, 415, 108, -1));
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(854, 559, 148, 114));
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    
    public void requestSummaryPlots()
    {
        int wipRequest=0, approvedRequest=0, totalRequests=0;
        for(PHDHospitalApproval list : phde.getHospitalApprovalList())
        {
           if(list.getHospitalStatus().equals("Approved"))
           {
               approvedRequest++;
           }
           if(list.getHospitalStatus().equals("Waiting for PHD Approval"))
           {
               wipRequest++;
           }
        }
        totalRequests = approvedRequest + wipRequest;
        lblTotal.setText(String.valueOf(totalRequests));
        lblApprove.setText(String.valueOf(approvedRequest));
        lblPending.setText(String.valueOf(wipRequest));
       
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        dataset.setValue(approvedRequest, "", "Approved");
        dataset.setValue(wipRequest, "", "pending");
        JFreeChart chart = ChartFactory.createBarChart("Total request from Hospitals for Approval.", "", "", dataset, PlotOrientation.VERTICAL, false, true, false);
        CategoryPlot catPlot = chart.getCategoryPlot();
        catPlot.setRangeGridlinePaint(Color.BLACK);
        ChartFrame frame = new ChartFrame("Bar Chart for hospital requests",chart);
        frame.setVisible(true);
        frame.setSize(650,350);  
    }
    
    
    private void btnSummaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSummaryActionPerformed
        // TODO add your handling code here:
        requestSummaryPlots();       
    }//GEN-LAST:event_btnSummaryActionPerformed

    private void btnApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveActionPerformed
        // TODO add your handling code here:
        
        if (tblHos.getSelectedRow() >= 0) {
            btnApprove.setEnabled(true);
            PHDHospitalApproval hosRequestApproval = (PHDHospitalApproval) tblHos.getValueAt(tblHos.getSelectedRow(), 0);

            for (Enterprise hospitalEnterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                
                if (hosRequestApproval.getHospitalEnterprise().equals(hospitalEnterprise)) {
                    hosRequestApproval.getHospitalEnterprise().setHospitalApproved(true);
                    ((HospitalEnterprise) hospitalEnterprise).setHospitalApproved(true);
                    hosRequestApproval.setHospitalStatus("Approved");
                    break;
                }
                
            }
              JOptionPane.showMessageDialog(null, "Hospital Approved successfully.", "Warning", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Select a hospital to Approve!");
        }
        populateHospitalTable();
        btnApprove.setEnabled(false);
    }//GEN-LAST:event_btnApproveActionPerformed

    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApprove;
    private javax.swing.JButton btnSummary;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lblApprove;
    private javax.swing.JTextField lblPending;
    private javax.swing.JTextField lblTotal;
    private javax.swing.JTable tblHos;
    // End of variables declaration//GEN-END:variables
}
