/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.PHD;

import Business.Organization.Organization;
import Business.Organization.OrganizationDirectory;
import java.awt.Image;
import java.nio.file.Paths;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bhargavi
 */
public class ManageOrganization extends javax.swing.JPanel {

    /**
     * Creates new form ManageOrganization
     */
    JPanel workArea;
    private OrganizationDirectory orgDirectory;

     private static final String AFILENAME = Paths.get("src").toAbsolutePath().toString();// path to the data store
    private String aimagePath = AFILENAME+"/Images/manage_org.png";
    public ManageOrganization(OrganizationDirectory dir, JPanel workArea) {
        initComponents();
        this.workArea = workArea;
        this.orgDirectory = dir;
         ImageIcon aimgIcon = new ImageIcon(aimagePath);
        Image aI = aimgIcon.getImage();
        Image aDimg = aI.getScaledInstance(90, 90,Image.SCALE_SMOOTH);
        ImageIcon aImgThisImg = new ImageIcon(aDimg);
        lblI.setIcon(aImgThisImg);
        
        populateOrgTable();
        populateOrgCB();
    }
    
    private void populateOrgTable(){
        DefaultTableModel model = (DefaultTableModel) tblOrg.getModel();
        
        model.setRowCount(0);
        
        for (Organization organization : orgDirectory.getOrganizationList()){
            Object[] row = new Object[1];
            row[0] = organization.getName();
            model.addRow(row);
        }
    }
     private void populateOrgCB(){
         cbOrg.removeAllItems();
         cbOrg.addItem(Organization.Type.PHDOrderOrganization);
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrg = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        cbOrg = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblI = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1100, 800));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblOrg.setBackground(new java.awt.Color(255, 156, 141));
        tblOrg.setForeground(new java.awt.Color(255, 255, 255));
        tblOrg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Name"
            }
        ));
        jScrollPane1.setViewportView(tblOrg);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 281, 100));

        jLabel2.setText("Organization type :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, -1, -1));

        cbOrg.setBackground(new java.awt.Color(255, 156, 141));
        cbOrg.setForeground(new java.awt.Color(255, 255, 255));
        cbOrg.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cbOrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 320, 128, -1));

        jButton1.setBackground(new java.awt.Color(255, 156, 141));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Add Organization");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 380, 160, 30));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 156, 141));
        jLabel1.setText("Manage Organization");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, -1, -1));
        add(lblI, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 520, 140, 130));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Organization.Type type = (Organization.Type) cbOrg.getSelectedItem();
        orgDirectory.createOrganization(type);
        populateOrgTable();
        JOptionPane.showMessageDialog(null, "New Organization added successfully!", "Warning", JOptionPane.INFORMATION_MESSAGE);
    
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbOrg;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblI;
    private javax.swing.JTable tblOrg;
    // End of variables declaration//GEN-END:variables
}
