/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI.PHD;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.PHDEnterprise;
import Business.Network.Network;
import UI.MainLoginJFrame;
import UI.SystemAdminWorkArea.ManageNetworkJPanel;
import java.awt.CardLayout;
import java.awt.Image;
import java.nio.file.Paths;
import javax.swing.ImageIcon;

/**
 *
 * @author Krishnakanth Naik Jarapala
 */
public class PHDAdminWorkArea extends javax.swing.JFrame {

    /**
     * Creates new form PhdWorkArea
     */
    private PHDEnterprise phdent;
    private EcoSystem system;
    private Network network;
    
     private static final String logoFILENAME = Paths.get("src").toAbsolutePath().toString();// path to the data store
    private String logoImagePath = logoFILENAME+"/Images/logout_blue.png";
    
    private static final String GFILENAME = Paths.get("src").toAbsolutePath().toString();// path to the data store
    private String bgimagePath = GFILENAME+"/Images/my-gradient.png";
    
    private static final String AFILENAME = Paths.get("src").toAbsolutePath().toString();// path to the data store
    private String aimagePath = AFILENAME+"/Images/sysadmin.png";
    
    public PHDAdminWorkArea(EcoSystem sys, Enterprise enterprise, Network network) {
        initComponents();
        
        phdent = (PHDEnterprise) enterprise;
        this.system= sys;
        this.network = network;
        
         ImageIcon bimgIcon = new ImageIcon(bgimagePath);
        Image bI = bimgIcon.getImage();
        Image cDimg = bI.getScaledInstance(200, 800,Image.SCALE_SMOOTH);
        ImageIcon cImgThisImg = new ImageIcon(cDimg);
        lblB.setIcon(cImgThisImg);
        
         ImageIcon logoimgIcon = new ImageIcon(logoImagePath);
        Image lI = logoimgIcon.getImage();
        Image logoDimg = lI.getScaledInstance(30, 30,Image.SCALE_SMOOTH);
        ImageIcon logoImgThisImg = new ImageIcon(logoDimg);
        lblL.setIcon(logoImgThisImg);
        
        ImageIcon aimgIcon = new ImageIcon(aimagePath);
        Image aI = aimgIcon.getImage();
        Image aDimg = aI.getScaledInstance(60, 60,Image.SCALE_SMOOTH);
        ImageIcon aImgThisImg = new ImageIcon(aDimg);
        lblAI.setIcon(aImgThisImg);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        controlPanel = new javax.swing.JPanel();
        btnOrg = new javax.swing.JButton();
        btnEmp = new javax.swing.JButton();
        btnUsers = new javax.swing.JButton();
        btnRequest = new javax.swing.JButton();
        lblL = new javax.swing.JLabel();
        lblT = new javax.swing.JLabel();
        lblAI = new javax.swing.JLabel();
        lblB = new javax.swing.JLabel();
        workArea = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setPreferredSize(new java.awt.Dimension(1300, 800));

        controlPanel.setPreferredSize(new java.awt.Dimension(200, 800));
        controlPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnOrg.setText("Manage Organisation");
        btnOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrgActionPerformed(evt);
            }
        });
        controlPanel.add(btnOrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 201, 178, -1));

        btnEmp.setText("Manage Employee");
        btnEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpActionPerformed(evt);
            }
        });
        controlPanel.add(btnEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 242, 178, -1));

        btnUsers.setText("Manage Users");
        btnUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsersActionPerformed(evt);
            }
        });
        controlPanel.add(btnUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 283, 178, -1));

        btnRequest.setText("Manage Requests");
        btnRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestActionPerformed(evt);
            }
        });
        controlPanel.add(btnRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 324, 178, -1));

        lblL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLMouseClicked(evt);
            }
        });
        controlPanel.add(lblL, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, 70, 50));

        lblT.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblT.setText("PHD Admin");
        controlPanel.add(lblT, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 100, 30));
        controlPanel.add(lblAI, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 100, 70));

        lblB.setPreferredSize(new java.awt.Dimension(200, 800));
        controlPanel.add(lblB, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 690));

        jSplitPane1.setLeftComponent(controlPanel);

        workArea.setPreferredSize(new java.awt.Dimension(1100, 800));
        workArea.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(workArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1194, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 687, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrgActionPerformed
        // TODO add your handling code here:
        ManageOrganization mnp = new ManageOrganization(phdent.getOrganizationDirectory(), workArea);
        workArea.add("manageNetworkJPanel", mnp);
        CardLayout cardlayout = (CardLayout) workArea.getLayout();
        cardlayout.next(workArea);        
    }//GEN-LAST:event_btnOrgActionPerformed

    private void btnEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpActionPerformed
        // TODO add your handling code here:
        ManageEmployee moe = new ManageEmployee(phdent.getOrganizationDirectory(), workArea);
        workArea.add("manageNetworkJPanel", moe);
        CardLayout cardlayout = (CardLayout) workArea.getLayout();
        cardlayout.next(workArea);  
        
        
    }//GEN-LAST:event_btnEmpActionPerformed

    private void btnUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsersActionPerformed
        // TODO add your handling code here:
        ManageUser mou = new ManageUser(phdent, workArea);
        workArea.add("manageNetworkJPanel", mou);
        CardLayout cardlayout = (CardLayout) workArea.getLayout();
        cardlayout.next(workArea);
    }//GEN-LAST:event_btnUsersActionPerformed

    private void btnRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestActionPerformed
        // TODO add your handling code here:
        ApproveHospital aoh = new ApproveHospital(phdent, network, workArea);
        workArea.add("manageNetworkJPanel", aoh);
        CardLayout cardlayout = (CardLayout) workArea.getLayout();
        cardlayout.next(workArea);
    }//GEN-LAST:event_btnRequestActionPerformed

    private void lblLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLMouseClicked
        // TODO add your handling code here:
         this.setVisible(false);
        MainLoginJFrame ml = new MainLoginJFrame(system,network);
        ml.setVisible(true); 
    }//GEN-LAST:event_lblLMouseClicked

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(PHDAdminWorkArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(PHDAdminWorkArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(PHDAdminWorkArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(PHDAdminWorkArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new PHDAdminWorkArea().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEmp;
    private javax.swing.JButton btnOrg;
    private javax.swing.JButton btnRequest;
    private javax.swing.JButton btnUsers;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblAI;
    private javax.swing.JLabel lblB;
    private javax.swing.JLabel lblL;
    private javax.swing.JLabel lblT;
    private javax.swing.JPanel workArea;
    // End of variables declaration//GEN-END:variables
}
