/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.SystemAdminWorkArea;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.HospitalEnterprise;
import Business.Enterprise.PHDEnterprise;
import Business.Network.Network;
import Business.WorkQueue.PHDHospitalApproval;
import java.awt.Image;
import java.nio.file.Paths;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bhargavi
 */
public class ManageEnterpriseJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageEnterpriseJPanel
     */
    EcoSystem system;
    JPanel workArea;
     private static final String AFILENAME = Paths.get("src").toAbsolutePath().toString();// path to the data store
    private String aimagePath = AFILENAME+"/Images/enterprise_icon.png";
    public ManageEnterpriseJPanel(EcoSystem sys, JPanel workArea) {
        initComponents();
        this.workArea = workArea;
;
        this.system = sys;
        
        populateEntTable();
        populateComboBoxes();
        ImageIcon aimgIcon = new ImageIcon(aimagePath);
        Image aI = aimgIcon.getImage();
        Image aDimg = aI.getScaledInstance(90, 90,Image.SCALE_SMOOTH);
        ImageIcon aImgThisImg = new ImageIcon(aDimg);
        lblI.setIcon(aImgThisImg);
        
        
//        btnU.setEnabled(false);
//        btnA.setEnabled(true);
//        btnD.setEnabled(false);
    }
    private void populateEntTable() {
        DefaultTableModel model = (DefaultTableModel) tblEnt.getModel();

        model.setRowCount(0);
        for (Network network : system.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                Object[] row = new Object[3];
                row[0] = enterprise.getName();
                row[1] = network.getName();
                row[2] = enterprise.getEnterpriseType().getValue();

                model.addRow(row);
            }
        }
    }

    private void populateComboBoxes() {
        cbNetwork.removeAllItems();
        cbEnterpriseName.removeAllItems();
        
        
        for (Network network : system.getNetworkList()) {
            cbNetwork.addItem(network);
        }
        
        for (Enterprise.EnterpriseType type : Enterprise.EnterpriseType.values()) {
            cbEnterpriseName.addItem(type);
        }
        


    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEnt = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbNetwork = new javax.swing.JComboBox();
        cbEnterpriseName = new javax.swing.JComboBox();
        txtName = new javax.swing.JTextField();
        btnA = new javax.swing.JButton();
        lblI = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1100, 800));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 156, 141));
        jLabel1.setText("Manage Enterprise");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, -1, -1));

        tblEnt.setBackground(new java.awt.Color(255, 156, 141));
        tblEnt.setForeground(new java.awt.Color(255, 255, 255));
        tblEnt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Enterprise Name", "Network", "Type"
            }
        ));
        tblEnt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEntMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEnt);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 498, 100));

        jLabel2.setText("Network :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, -1, -1));

        jLabel3.setText("Enterprise Type :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, -1, -1));

        jLabel4.setText("Name :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, -1, -1));

        cbNetwork.setBackground(new java.awt.Color(255, 156, 141));
        cbNetwork.setForeground(new java.awt.Color(255, 255, 255));
        add(cbNetwork, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 280, 141, -1));

        cbEnterpriseName.setBackground(new java.awt.Color(255, 156, 141));
        cbEnterpriseName.setForeground(new java.awt.Color(255, 255, 255));
        cbEnterpriseName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEnterpriseNameActionPerformed(evt);
            }
        });
        add(cbEnterpriseName, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 330, 141, -1));

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 380, 141, -1));

        btnA.setBackground(new java.awt.Color(255, 156, 141));
        btnA.setForeground(new java.awt.Color(255, 255, 255));
        btnA.setText("Submit");
        btnA.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAActionPerformed(evt);
            }
        });
        add(btnA, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 440, 120, 30));
        add(lblI, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 560, 150, 160));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAActionPerformed
        // TODO add your handling code here:
        
        
        
        if (txtName.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter Enterprise Name.");
        } else {

            Network network = (Network) cbNetwork.getSelectedItem();
            Enterprise.EnterpriseType type = (Enterprise.EnterpriseType) cbEnterpriseName.getSelectedItem();

            if (network == null || type == null) {
                JOptionPane.showMessageDialog(null, "Invalid Input!");
                return;
            }
            /// if trying to Create hospital check for PHD existance.
            boolean typeHospital = false;
            PHDEnterprise phde = null;
            int count = 0;
            if (type.equals(Enterprise.EnterpriseType.Hospital)) {
                typeHospital = true;
                for (Enterprise enterprisePHD : network.getEnterpriseDirectory().getEnterpriseList()) {
                    if (enterprisePHD instanceof PHDEnterprise) {
                        //((PHDEnterprise) enterprisePHD).getHospitalApprovalArrayList().);
                        phde = (PHDEnterprise) enterprisePHD;
                        count++;
                        //return;
                    }
                }
            } else {
                String name = txtName.getText().toUpperCase();
                Enterprise enterprise = network.getEnterpriseDirectory().createAndAddEnterprise(type, name);
            }
            
            
//          If the enterprise is hospital then check for PHD existance then create approval request for the hospital.

            if (typeHospital) {
                if (phde == null) {
                    JOptionPane.showMessageDialog(null, "Kindly create PHD Enterprise first");
                } else if (phde != null && typeHospital && count == 1) {
                    String name = txtName.getText().toUpperCase();
//                    System.out.println("Hospital Name " + name);
                    Enterprise enterprise = network.getEnterpriseDirectory().createAndAddEnterprise(type, name);
                    HospitalEnterprise hospitalEnterprise = (HospitalEnterprise) enterprise;

                    PHDHospitalApproval phdHospitalApproval = new PHDHospitalApproval();
                    phdHospitalApproval.setHospitalEnterprise((HospitalEnterprise) hospitalEnterprise);
                    ((HospitalEnterprise) hospitalEnterprise).setHospitalApproved(false);
                    phdHospitalApproval.setHospitalStatus("Waiting for PHD Approval");
                    phde.getHospitalApprovalList().add(phdHospitalApproval);
                }
            }
            txtName.setEnabled(true);
            txtName.setText("");
            populateEntTable();
            JOptionPane.showMessageDialog(null, "Enterprise added successfully.", "Warning", JOptionPane.INFORMATION_MESSAGE);
        }
        
        
        
//        if (txtName.getText().equals("")) {
//            JOptionPane.showMessageDialog(null, "Please enter the Enterprise Name!");
//        } else {
//
//            Network network = (Network) cbNetwork.getSelectedItem();
//            Enterprise.EnterpriseType type = (Enterprise.EnterpriseType) cbEnterpriseName.getSelectedItem();
//
//            if (network == null || type == null) {
//                JOptionPane.showMessageDialog(null, "Please select Network and Enterprise.");
//                return;
//            }
//            
//            /// if trying to Create hospital check for PHD existance.
//            boolean typeHospital = false;
//            PHDEnterprise phde = null;
//            int count = 0;
//            
////            Checking the Hospital Enterprise
//            if (type.equals(Enterprise.EnterpriseType.Hospital)) {
//                typeHospital = true;
//                for (Enterprise enterprisePHD : network.getEnterpriseDirectory().getEnterpriseList()) {
//                    if (enterprisePHD instanceof PHDEnterprise) {
//                        //((PHDEnterprise) enterprisePHD).getHospitalApprovalArrayList().);
//                        phde = (PHDEnterprise) enterprisePHD;
//                        count++;
//                        //return;
//                    }
//                }
//            }
//            else {
//                String name = txtName.getText();
//                Enterprise enterprise = network.getEnterpriseDirectory().createAndAddEnterprise(type, name);
//            }
//            
////            If the enterprise is hospital then check for PHD existance then create approval request for the hospital.
//            if (typeHospital) {
//                if (phde == null) {
//                    JOptionPane.showMessageDialog(null, "Kindly create a PHD Enterprise before creating a Hospital.");
//                } else if (phde != null && typeHospital && count == 1) {
//                    String name = txtName.getText();
//                    Enterprise enterprise = network.getEnterpriseDirectory().createAndAddEnterprise( type, name);
//                    HospitalEnterprise hospitalEnterprise = (HospitalEnterprise) enterprise;
//
//                    PHDHospitalApproval phdHospitalApproval = new PHDHospitalApproval();
//                    phdHospitalApproval.setHospitalEnterprise((HospitalEnterprise) hospitalEnterprise);
//                    ((HospitalEnterprise) hospitalEnterprise).setHospitalApproved(false);
//                    phdHospitalApproval.setHospitalStatus("Requested to PHD for Approval of the Hospital!");
//                    phde.getHospitalApprovalList().add(phdHospitalApproval);
//                }
//            }
//            txtName.setText("");
//            cbNetwork.setSelectedIndex(-1);
//            cbEnterpriseName.setSelectedIndex(-1);
//
//            populateEntTable();
//            JOptionPane.showMessageDialog(null, "Enterprise added successfully.", "Warning", JOptionPane.INFORMATION_MESSAGE);
//        }
        
    }//GEN-LAST:event_btnAActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void cbEnterpriseNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEnterpriseNameActionPerformed
        // TODO add your handling code here:
        if((cbEnterpriseName.getSelectedItem().toString() == "CDC") || (cbEnterpriseName.getSelectedItem().toString() == "PHD") ){
            txtName.setEnabled(false);
            txtName.setText(cbEnterpriseName.getSelectedItem().toString());
            
        }
        else{
            txtName.setEnabled(true);
            txtName.setText("");
        }
    }//GEN-LAST:event_cbEnterpriseNameActionPerformed

    private void tblEntMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEntMouseClicked
        // TODO add your handling code here:
//        
//        int selectedRow = tblEnt.getSelectedRow();
//        
//        if (selectedRow < 0) {
//            JOptionPane.showMessageDialog(null, "Please select a Network to Manage.", "Warning", JOptionPane.WARNING_MESSAGE);
//        } 
//        else{
//            
//            Enterprise ent = (Enterprise) tblEnt.getValueAt(selectedRow, 0);
//            ent.get
//            
//            System.out.println("Select Network: "+net.getName().toUpperCase());
//            tblEnt.setText(net.getName());
//            btnU.setEnabled(true);
//            btnA.setEnabled(false);
//            btnD.setEnabled(true);
//        }
        
    }//GEN-LAST:event_tblEntMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnA;
    private javax.swing.JComboBox cbEnterpriseName;
    private javax.swing.JComboBox cbNetwork;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblI;
    private javax.swing.JTable tblEnt;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
