/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.SystemAdminWorkArea;
import Business.EcoSystem;
import Business.Network.Network;
import java.awt.Color;
import java.awt.Image;
import java.nio.file.Paths;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
/**
 *
 * @author bhargavi
 */
public class ManageNetworkJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageNetworkJPanel
     */
    EcoSystem system;
    JPanel WorkArea;
      private static final String logoFILENAME = Paths.get("src").toAbsolutePath().toString();// path to the data store
    private String logoImagePath = logoFILENAME+"/Images/network.png";
    
     private static final String AFILENAME = Paths.get("src").toAbsolutePath().toString();// path to the data store
    private String aimagePath = AFILENAME+"/Images/network_icon.png";
    public ManageNetworkJPanel(EcoSystem system, JPanel workArea) {
        initComponents();
        this.WorkArea = workArea;
        this.system = system;
        populateNetworkTable();
        ImageIcon logoimgIcon = new ImageIcon(logoImagePath);
        Image lI = logoimgIcon.getImage();
        Image logoDimg = lI.getScaledInstance(600, 600,Image.SCALE_SMOOTH);
        ImageIcon logoImgThisImg = new ImageIcon(logoDimg);
        lblN.setIcon(logoImgThisImg);
        
        ImageIcon aimgIcon = new ImageIcon(aimagePath);
        Image aI = aimgIcon.getImage();
        Image aDimg = aI.getScaledInstance(90, 90,Image.SCALE_SMOOTH);
        ImageIcon aImgThisImg = new ImageIcon(aDimg);
        lblI.setIcon(aImgThisImg);
        
//        JTableHeader theader = tblNetwork.getTableHeader();
//        theader.setBackground(Color.black);
        
        JTableHeader tableHeader = tblNetwork.getTableHeader();
      tableHeader.setBackground(Color.black);
    }
    
    private void populateNetworkTable() {
        DefaultTableModel model = (DefaultTableModel) tblNetwork.getModel();
        model.setRowCount(0);
        for (Network network : system.getNetworkList()) {
            Object[] row = new Object[1];
            row[0] = network.getName();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        tblNetwork = new javax.swing.JTable();
        lblNetworkName = new javax.swing.JLabel();
        txtNetworkName = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblN = new javax.swing.JLabel();
        lblI = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1100, 800));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 156, 141));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Manage Network");
        lblTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblTitle.setRequestFocusEnabled(false);
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 210, -1));

        jScrollPane.setBackground(new java.awt.Color(255, 156, 141));

        tblNetwork.setBackground(new java.awt.Color(255, 156, 141));
        tblNetwork.setForeground(new java.awt.Color(255, 255, 255));
        tblNetwork.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Name"
            }
        ));
        tblNetwork.setGridColor(new java.awt.Color(255, 156, 141));
        tblNetwork.setSelectionBackground(new java.awt.Color(255, 156, 141));
        tblNetwork.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane.setViewportView(tblNetwork);

        add(jScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 370, 100));

        lblNetworkName.setFont(new java.awt.Font("Arial Black", 1, 15)); // NOI18N
        lblNetworkName.setForeground(new java.awt.Color(255, 156, 141));
        lblNetworkName.setText("Network Name :");
        add(lblNetworkName, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 140, -1));

        txtNetworkName.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(txtNetworkName, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, 180, 30));

        btnAdd.setBackground(new java.awt.Color(255, 156, 141));
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Add");
        btnAdd.setBorder(null);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 140, 30));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setPreferredSize(new java.awt.Dimension(1100, 800));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 560));
        add(lblN, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 480, 390));
        add(lblI, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 540, 150, 140));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        
        if(txtNetworkName.getText().equalsIgnoreCase(""))
        {
           JOptionPane.showMessageDialog(null, "Please enter the Network Name.");
        }
        else
        {
        String name = txtNetworkName.getText().toUpperCase();
        Network network = system.createAndAddNetwork();
        network.setName(name);
        populateNetworkTable();
        txtNetworkName.setText("");
        JOptionPane.showMessageDialog(null, "Network added successfully.", "Warning", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnAddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JLabel lblI;
    private javax.swing.JLabel lblN;
    private javax.swing.JLabel lblNetworkName;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblNetwork;
    private javax.swing.JTextField txtNetworkName;
    // End of variables declaration//GEN-END:variables
}
