/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.SystemAdminWorkArea;
import Business.Disease.Disease;
import Business.EcoSystem;
import Business.Network.Network;
import Business.WorkQueue.ReceptionWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.Color;
import java.awt.Image;
import java.nio.file.Paths;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
/**
 *
 * @author bhargavi
 */
public class ManageNetworkJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageNetworkJPanel
     */
    EcoSystem system;
    JPanel WorkArea;
      private static final String logoFILENAME = Paths.get("src").toAbsolutePath().toString();// path to the data store
    private String logoImagePath = logoFILENAME+"/Images/network.png";
    
     private static final String AFILENAME = Paths.get("src").toAbsolutePath().toString();// path to the data store
    private String aimagePath = AFILENAME+"/Images/network_icon.png";
    public ManageNetworkJPanel(EcoSystem system, JPanel workArea) {
        initComponents();
        this.WorkArea = workArea;
        this.system = system;
        populateNetworkTable();
        
//        Image Populating code
        ImageIcon logoimgIcon = new ImageIcon(logoImagePath);
        Image lI = logoimgIcon.getImage();
        Image logoDimg = lI.getScaledInstance(600, 600,Image.SCALE_SMOOTH);
        ImageIcon logoImgThisImg = new ImageIcon(logoDimg);
        lblN.setIcon(logoImgThisImg);
        
        ImageIcon aimgIcon = new ImageIcon(aimagePath);
        Image aI = aimgIcon.getImage();
        Image aDimg = aI.getScaledInstance(90, 90,Image.SCALE_SMOOTH);
        ImageIcon aImgThisImg = new ImageIcon(aDimg);
        lblI.setIcon(aImgThisImg);
        
//        JTableHeader theader = tblNetwork.getTableHeader();
//        theader.setBackground(Color.black);
        
        JTableHeader tableHeader = tblNetwork.getTableHeader();
        tableHeader.setBackground(Color.black);
        
        btnU.setEnabled(false);
        btnA.setEnabled(true);
        btnD.setEnabled(false);
    }
    
    private void populateNetworkTable() {
        DefaultTableModel model = (DefaultTableModel) tblNetwork.getModel();
        model.setRowCount(0);
        for (Network network : system.getNetworkList()) {
            Object[] row = new Object[1];
            row[0] = network;
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        tblNetwork = new javax.swing.JTable();
        lblNetworkName = new javax.swing.JLabel();
        txtNetworkName = new javax.swing.JTextField();
        btnA = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblN = new javax.swing.JLabel();
        lblI = new javax.swing.JLabel();
        btnU = new javax.swing.JButton();
        btnD = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1100, 800));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 156, 141));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Manage Network");
        lblTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblTitle.setRequestFocusEnabled(false);
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 210, -1));

        jScrollPane.setBackground(new java.awt.Color(255, 156, 141));

        tblNetwork.setBackground(new java.awt.Color(255, 156, 141));
        tblNetwork.setForeground(new java.awt.Color(255, 255, 255));
        tblNetwork.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Name"
            }
        ));
        tblNetwork.setGridColor(new java.awt.Color(255, 156, 141));
        tblNetwork.setSelectionBackground(new java.awt.Color(255, 156, 141));
        tblNetwork.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tblNetwork.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNetworkMouseClicked(evt);
            }
        });
        jScrollPane.setViewportView(tblNetwork);

        add(jScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 370, 100));

        lblNetworkName.setFont(new java.awt.Font("Arial Black", 1, 15)); // NOI18N
        lblNetworkName.setForeground(new java.awt.Color(255, 156, 141));
        lblNetworkName.setText("Network Name :");
        add(lblNetworkName, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 140, -1));

        txtNetworkName.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(txtNetworkName, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, 180, 30));

        btnA.setBackground(new java.awt.Color(255, 156, 141));
        btnA.setForeground(new java.awt.Color(255, 255, 255));
        btnA.setText("Add");
        btnA.setBorder(null);
        btnA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAActionPerformed(evt);
            }
        });
        add(btnA, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 140, 30));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setPreferredSize(new java.awt.Dimension(1100, 800));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 570));
        add(lblN, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 480, 370));
        add(lblI, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 540, 150, 140));

        btnU.setBackground(new java.awt.Color(255, 156, 141));
        btnU.setForeground(new java.awt.Color(255, 255, 255));
        btnU.setText("Update");
        btnU.setBorder(null);
        btnU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUActionPerformed(evt);
            }
        });
        add(btnU, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 350, 140, 30));

        btnD.setBackground(new java.awt.Color(255, 156, 141));
        btnD.setForeground(new java.awt.Color(255, 255, 255));
        btnD.setText("Delete");
        btnD.setBorder(null);
        btnD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDActionPerformed(evt);
            }
        });
        add(btnD, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 350, 140, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAActionPerformed
        // TODO add your handling code here:
        
        if(txtNetworkName.getText().equalsIgnoreCase(""))
        {
           JOptionPane.showMessageDialog(null, "Please enter the Network Name.");
        }
        else
        {
        String name = txtNetworkName.getText().toUpperCase();
        Network network = system.createAndAddNetwork();
        network.setName(name);
        populateNetworkTable();
        txtNetworkName.setText("");
        JOptionPane.showMessageDialog(null, "Network added successfully.", "Warning", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnAActionPerformed

    private void tblNetworkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNetworkMouseClicked
        // TODO add your handling code here:
        int selectedRow = tblNetwork.getSelectedRow();
        
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a Network to Manage.", "Warning", JOptionPane.WARNING_MESSAGE);
        } 
        else{
            
            Network net = (Network) tblNetwork.getValueAt(selectedRow, 0);
            System.out.println("Select Network: "+net.getName().toUpperCase());
            txtNetworkName.setText(net.getName());
            btnU.setEnabled(true);
            btnA.setEnabled(false);
//            btnD.setEnabled(true);
        }
        
         
        
    }//GEN-LAST:event_tblNetworkMouseClicked

    private void btnUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblNetwork.getSelectedRow();
        Network net = (Network) tblNetwork.getValueAt(selectedRow, 0);
        System.out.println("Select Network: "+net.getName().toUpperCase());
        String name = txtNetworkName.getText().toUpperCase();
        
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a Network to Remove.", "Warning", JOptionPane.WARNING_MESSAGE);
        } 
        else{
            if(name.length() > 2){
                net.setName(name);
                System.out.println("New Network Name: " + net.getName().toUpperCase());
                btnU.setEnabled(false);
                btnA.setEnabled(true);
                btnD.setEnabled(false);
            }
            else{
                JOptionPane.showMessageDialog(null, "Enter a valid name");
            }

        }
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_btnUActionPerformed

    private void btnDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblNetwork.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a Network to delete.", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {

            Network net = (Network) tblNetwork.getValueAt(selectedRow, 0);

            system.removeNetwork(net);
            JOptionPane.showMessageDialog(null, "Successfully deleted the network from the System");
            populateNetworkTable();
            txtNetworkName.setText("");
            btnU.setEnabled(false);
            btnA.setEnabled(true);
            btnD.setEnabled(false);
            
        }
        
        
    }//GEN-LAST:event_btnDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnA;
    private javax.swing.JButton btnD;
    private javax.swing.JButton btnU;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JLabel lblI;
    private javax.swing.JLabel lblN;
    private javax.swing.JLabel lblNetworkName;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblNetwork;
    private javax.swing.JTextField txtNetworkName;
    // End of variables declaration//GEN-END:variables
}
