/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.SystemAdminWorkArea;

import Business.Disease.Disease;
import Business.EcoSystem;
import Business.vaccine.Vaccine;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bhargavi
 */
public class ManageVaccineJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageVaccineJPanel
     */
    EcoSystem system;
    JPanel WorkArea;
    Disease tempDisease;
    public ManageVaccineJPanel(EcoSystem sys, JPanel workArea) {
        initComponents(); 
        this.WorkArea = workArea;
        this.system  = sys;       
        populateVaccineTable();
        populateComboBox();
    }
    
    public void populateVaccineTable(){
         DefaultTableModel dtm= (DefaultTableModel) tblVaccine.getModel();
       dtm.setRowCount(0);
       for (Vaccine vaccine : system.getVaccineDirectory().getVaccineList()) {        
           Object[] row = new Object[3];
           row[0]= vaccine;
           row[1]=vaccine.getVaccineId();
           row[2]= vaccine.getPrice();
           dtm.addRow(row);
       }  
       }
    
    public void populateComboBox(){
        for (Disease disease : system.getDiseaseDirectory().getDiseaseList()) {
            cbDisease.addItem(disease);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVaccine = new javax.swing.JTable();
        btnDeleteVaccine = new javax.swing.JButton();
        lblName = new javax.swing.JLabel();
        lblDisease = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        cbDisease = new javax.swing.JComboBox();
        btnAddVaccine = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1100, 800));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblTitle.setText("Manage Vaccine");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 41, -1, -1));

        tblVaccine.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Vaccine Name", "Vaccine ID", "Price"
            }
        ));
        jScrollPane1.setViewportView(tblVaccine);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 140, 504, 100));

        btnDeleteVaccine.setText("Delete Vaccine");
        btnDeleteVaccine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteVaccineActionPerformed(evt);
            }
        });
        add(btnDeleteVaccine, new org.netbeans.lib.awtextra.AbsoluteConstraints(553, 252, -1, -1));

        lblName.setText("Name :");
        add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 300, -1, -1));

        lblDisease.setText("Disease :");
        add(lblDisease, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 351, -1, -1));

        lblPrice.setText("Price :");
        add(lblPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 397, -1, -1));

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 297, 161, -1));
        add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 394, 161, -1));

        cbDisease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDiseaseActionPerformed(evt);
            }
        });
        add(cbDisease, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 348, 161, -1));

        btnAddVaccine.setText("Add Vaccine");
        btnAddVaccine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddVaccineActionPerformed(evt);
            }
        });
        add(btnAddVaccine, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 462, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteVaccineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteVaccineActionPerformed
        // TODO add your handling code here:
        
        int selectedRow= tblVaccine.getSelectedRow();
        if(selectedRow<0)
        {
            JOptionPane.showMessageDialog(null, "Please select the Vaccine to be Deleted from Vaccine Directory.", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else
        {

            Vaccine vac=(Vaccine) tblVaccine.getValueAt(selectedRow, 0);

            system.getVaccineDirectory().deleteVaccine(vac);

            JOptionPane.showMessageDialog(null, "Successfully deleted the Vaccine.");
            populateVaccineTable();
        }
    }//GEN-LAST:event_btnDeleteVaccineActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void btnAddVaccineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddVaccineActionPerformed
        // TODO add your handling code here:
        
        
        if(txtName.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please enter vaccine Name");
        }
        else if(Float.parseFloat(txtPrice.getText()) < 0){
            JOptionPane.showMessageDialog(null, "Price cannot be less than 0.");
        }
        else
        {          
            
            Vaccine v= system.getVaccineDirectory().addVaccine();
            v.setVaccineName(txtName.getText());
            v.setDisease((Disease) cbDisease.getSelectedItem());
            v.setPrice(Float.parseFloat(txtPrice.getText()));
            populateVaccineTable();
            txtName.setText("");
            txtPrice.setText("");
            cbDisease.setSelectedIndex(-1);
            JOptionPane.showMessageDialog(null, "Vaccine added successfully.", "Warning", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnAddVaccineActionPerformed

    private void cbDiseaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDiseaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbDiseaseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddVaccine;
    private javax.swing.JButton btnDeleteVaccine;
    private javax.swing.JComboBox cbDisease;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDisease;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblVaccine;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrice;
    // End of variables declaration//GEN-END:variables
}
