/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.SystemAdminWorkArea;

import Business.Disease.Disease;
import Business.EcoSystem;
import java.awt.Image;
import java.nio.file.Paths;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bhargavi
 */
public class ManageDiseaseJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageDiseaseJPanel
     */
    
    EcoSystem system;
    JPanel WorkArea;
    
    private static final String GFILENAME = Paths.get("src").toAbsolutePath().toString();// path to the data store
    private String bgimagePath = GFILENAME+"/Images/disease_back.jpeg";
    
    private static final String AFILENAME = Paths.get("src").toAbsolutePath().toString();// path to the data store
    private String aimagePath = AFILENAME+"/Images/disease_icon.png";
    
    public ManageDiseaseJPanel(EcoSystem system, JPanel workArea) {
        initComponents();
        this.WorkArea = workArea;
        this.system = system;
        populateDiseaseTable();
        ImageIcon bimgIcon = new ImageIcon(bgimagePath);
        Image bI = bimgIcon.getImage();
        Image cDimg = bI.getScaledInstance(700, 800,Image.SCALE_SMOOTH);
        ImageIcon cImgThisImg = new ImageIcon(cDimg);
        lblB.setIcon(cImgThisImg);
        
         ImageIcon aimgIcon = new ImageIcon(aimagePath);
        Image aI = aimgIcon.getImage();
        Image aDimg = aI.getScaledInstance(90, 90,Image.SCALE_SMOOTH);
        ImageIcon aImgThisImg = new ImageIcon(aDimg);
        lblI.setIcon(aImgThisImg);
    }
    
    public void populateDiseaseTable() {
        DefaultTableModel dtm = (DefaultTableModel) tblDiseases.getModel();
        dtm.setRowCount(0);
        for (Disease disease : system.getDiseaseDirectory().getDiseaseList()) {
            Object[] row = new Object[1];
            row[0] = disease;
            dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDiseases = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtDisease = new javax.swing.JTextField();
        btnAddDisease = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        lblB = new javax.swing.JLabel();
        lblI = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1100, 800));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setBackground(new java.awt.Color(255, 255, 255));
        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(102, 102, 102));
        lblTitle.setText("Manage Disease");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, -1, -1));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        tblDiseases.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Disease"
            }
        ));
        jScrollPane1.setViewportView(tblDiseases);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 350, 100));

        jLabel2.setText("Disease :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, -1, -1));

        txtDisease.setForeground(new java.awt.Color(102, 102, 102));
        add(txtDisease, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 320, 146, -1));

        btnAddDisease.setForeground(new java.awt.Color(102, 102, 102));
        btnAddDisease.setText("Create New Disease");
        btnAddDisease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDiseaseActionPerformed(evt);
            }
        });
        add(btnAddDisease, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 380, -1, -1));

        btnDelete.setForeground(new java.awt.Color(102, 102, 102));
        btnDelete.setText("Delete Disease");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(602, 269, -1, -1));
        add(lblB, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 500, 380));
        add(lblI, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 540, 150, 130));
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        
        int selectedRow = tblDiseases.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select the Disease to delete from the System", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {

            Disease p = (Disease) tblDiseases.getValueAt(selectedRow, 0);

            system.getDiseaseDirectory().removeDisease(p);
            JOptionPane.showMessageDialog(null, "Successfully deleted the Disease from the System");
            populateDiseaseTable();
        }

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnAddDiseaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDiseaseActionPerformed
        // TODO add your handling code here:
        
        if(txtDisease.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please enter Disease Name.");
        }
         else
        {
        Disease v = system.getDiseaseDirectory().addDisease();
        v.setDiseaseName(txtDisease.getText());
        populateDiseaseTable();
        txtDisease.setText("");
          JOptionPane.showMessageDialog(null, "Disease added successfully.", "Warning", JOptionPane.INFORMATION_MESSAGE);
        }

        
        
        
    }//GEN-LAST:event_btnAddDiseaseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddDisease;
    private javax.swing.JButton btnDelete;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblB;
    private javax.swing.JLabel lblI;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblDiseases;
    private javax.swing.JTextField txtDisease;
    // End of variables declaration//GEN-END:variables
}
