/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.EventOrganisation;
import Business.Organization.Organization;
import Business.SubOrganization.SubOrganization;
import Business.UserAccount.UserAccount;
import UI.SystemAdminWorkArea.SystemAdminWorkArea;
import java.awt.CardLayout;
import java.awt.Image;
import java.nio.file.Paths;
import static java.time.Clock.system;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
/**
 *
 * @author Krishnakanth Naik Jarapala
 */
public class MainLoginJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainLoginJFrame
     */
    private EcoSystem system;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    private Network network;
    private static final String FILENAME = Paths.get("src").toAbsolutePath().toString();// path to the data store
    private String imagePath = FILENAME+"/Images/vaccine main page.jpeg";

//    /Users/bhargavi/VenkataBhargavi-Sikhakolli-002724793/AED_FINAL_PROJECT/AED_Final_Project/VaccineManagementSystem/vaccine main page.jpeg
    public MainLoginJFrame(){
        initComponents();
        system = dB4OUtil.retrieveSystem();
//        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setVisible(true);
        ImageIcon imgIcon = new ImageIcon(imagePath);
        Image i = imgIcon.getImage();
        Image dimg = i.getScaledInstance(1012, 533,Image.SCALE_SMOOTH);
        System.out.println(FILENAME);
        System.out.println(imagePath);
        ImageIcon imgThisImg = new ImageIcon(dimg);
        lblImage.setIcon(imgThisImg);

    }
    
    public MainLoginJFrame(EcoSystem system,Network network) {
        initComponents();
//        Storing the data to database
        setVisible(true);
        
        this.system = system;
        dB4OUtil.storeSystem(system);
//        setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titlebox = new javax.swing.JLabel();
        lbl_Password = new javax.swing.JLabel();
        lbl_username = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        pass_password = new javax.swing.JPasswordField();
        btn_login = new javax.swing.JButton();
        lblImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titlebox.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        titlebox.setForeground(new java.awt.Color(51, 51, 51));
        titlebox.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlebox.setText("Vaccine Management System");
        jPanel1.add(titlebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 35, 1006, 86));

        lbl_Password.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lbl_Password.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbl_Password.setText("Password:");
        jPanel1.add(lbl_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 239, 129, 45));

        lbl_username.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lbl_username.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbl_username.setText("Username:");
        jPanel1.add(lbl_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 176, 129, 45));

        txt_username.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jPanel1.add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(467, 176, 208, 45));

        pass_password.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        pass_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pass_passwordActionPerformed(evt);
            }
        });
        jPanel1.add(pass_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(467, 239, 208, 45));

        btn_login.setText("Login");
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        jPanel1.add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 318, 90, 39));
        jPanel1.add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1040, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pass_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pass_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pass_passwordActionPerformed

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        // TODO add your handling code here:
        
//        String role = comboBox_roleMenu.getSelectedItem().toString();
        
//        for(Patient pat: patientlist.getPatientlist()){
//            this.patientCred.put(pat.getUsername(), pat.getPassword());
//        }
//        
//        for(Doctor doc: doctorlist.getDoctorlist()){
//            this.doctorCred.put(doc.getUsername(), doc.getPassword());
//        }
        //doctorCred = doctorlist.getDoctorCredentails();
        //patientCred = patientlist.getPatientCredentails();
        
        
//        if((role.equals("System Admin")) && (txt_username.getText().equals("admin"))  && (pass_password.getText().equals("admin"))){
//            this.setVisible(false);
//            SystemAdminWorkArea sa = new SystemAdminWorkArea(system);
////            JOptionPane.showMessageDialog(this, "USER Credentials are correct!");
//            sa.setVisible(true);
//        }

        if (txt_username.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter Login Name.");
        } else if (pass_password.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter Login Password.");
        } 
        else {

            // Get user name
            String userName = txt_username.getText();
            String password = pass_password.getText();

            //Checking whether is user is an instance of enterprise.
            UserAccount userAccount = system.getUserAccountDirectory().authenticateUser(userName, password);
            // Initilizing the enterprise, org, suborg and user as null as we don't yet know where the user is working.
            UserAccount userAccounttoFind = null;
            Enterprise userEnterprise = null;
            Organization userOrganization = null;
            SubOrganization userSubOrganization = null;

            //            Loop to find whether the user is in Enterprise / Org / Suborg
            if(userAccount == null){
                //                if the user is not found, then checking in each enterprise by each network
                for(Network network: system.getNetworkList()){
                    for(Enterprise ent: network.getEnterpriseDirectory().getEnterpriseList()){
                        userAccount = ent.getUserAccountDirectory().authenticateUser(userName, password);
                        if (userAccount == null) {
                            //if user is not found in the enterprse, we drill down into each each organization for each enterprise
                            for (Organization org : ent.getOrganizationDirectory().getOrganizationList()) {
                                userAccount = org.getUserAccountDirectory().authenticateUser(userName, password);
                                if (userAccount == null) {
                                    if (org instanceof EventOrganisation && ((EventOrganisation) org).getEventSubOrganizationDirectory().getOrganizationList() != null) {
                                        // Similarly, checking in the suborg of each org.
                                        for (SubOrganization subOrganization : ((EventOrganisation) org).getEventSubOrganizationDirectory().getOrganizationList()) {
                                            userAccount = subOrganization.getUserAccountDirectory().authenticateUser(userName, password);
                                            if (userAccount != null) {
                                                userAccounttoFind = userAccount;
                                                userEnterprise = ent;
                                                userOrganization = org;
                                                this.network = network;
                                                userSubOrganization = subOrganization;
                                                System.out.println("organization ia an instance of EventOrganisation" + userAccount.getRole());
                                                System.out.println("organization is an instance of EventOrganisation" + userEnterprise);
                                                System.out.println("organization is an instance of EventOrganisation" + userSubOrganization);
                                                //System.out.println("organization instanceof EventOrganisation");
                                                break;
                                            }
                                        }
                                    }
                                    //                                    User found in a organization, so must be working in thespecific organization
                                    else if (userAccount != null) {
                                        userEnterprise = ent;
                                        userOrganization = org;
                                        this.network = network;
                                        System.out.println("organization is an instance of EventOrganisation" + userAccount.getRole());
                                        break;
                                        //}
                                }
                            } else if (userAccount != null) {
                                userEnterprise = ent;
                                userOrganization = org;
                                this.network = network;
                                break;
                            }
                        }
                    }
                    //                        Found the user in enterprise
                    else {
                        userEnterprise = ent;
                        this.network = network;
                        break;
                    }
                    if (userOrganization != null) {
                        break;
                    }
                }
                if (userEnterprise != null) {
                    break;
                }
                }
            }

        if(userAccount == null && userAccounttoFind == null){
            JOptionPane.showMessageDialog(null, "User not Found!, Please check Credentails!");
            return;
        }
        else if(userAccount == null && userAccounttoFind != null){
            JFrame workArea = userAccounttoFind.getRole().createWorkArea( userAccounttoFind, userOrganization, userEnterprise, system, network);
            workArea.setVisible(true);
            setVisible(false);
        }
        else{
            JOptionPane.showMessageDialog(null, "valid Credentails!");
            JFrame workArea = userAccount.getRole().createWorkArea( userAccounttoFind, userOrganization, userEnterprise, system, network);
            workArea.setVisible(true);
            setVisible(false);

        }
    }//GEN-LAST:event_btn_loginActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainLoginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainLoginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainLoginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainLoginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainLoginJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_login;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lbl_Password;
    private javax.swing.JLabel lbl_username;
    private javax.swing.JPasswordField pass_password;
    private javax.swing.JLabel titlebox;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
