/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI.CDC;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.OrganizationDirectory;
import UI.MainLoginJFrame;
import java.awt.CardLayout;
import java.awt.Image;
import java.nio.file.Paths;
import javax.swing.ImageIcon;

/**
 *
 * @author bhargavi
 */
public class CdcAdminWorkArea extends javax.swing.JFrame {

    /**
     * Creates new form CdcWorkArea
     */
    
    EcoSystem system;
    Enterprise enterprise;
    private OrganizationDirectory orgDirectory;
    Network network;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    private static final String AFILENAME = Paths.get("src").toAbsolutePath().toString();// path to the data store
    private String aimagePath = AFILENAME+"/Images/sysadmin.png";
    
     private static final String logoFILENAME = Paths.get("src").toAbsolutePath().toString();// path to the data store
    private String logoImagePath = logoFILENAME+"/Images/logout_blue.png";
    
     private static final String GFILENAME = Paths.get("src").toAbsolutePath().toString();// path to the data store
    private String bgimagePath = GFILENAME+"/Images/my-gradient.png";
    public CdcAdminWorkArea(EcoSystem system, Enterprise enterprise, Network network) {
        initComponents();
        this.system = system;
        this.enterprise = enterprise;
        this.network = network;
         ImageIcon aimgIcon = new ImageIcon(aimagePath);
        Image aI = aimgIcon.getImage();
        Image aDimg = aI.getScaledInstance(60, 60,Image.SCALE_SMOOTH);
        ImageIcon aImgThisImg = new ImageIcon(aDimg);
        lblA.setIcon(aImgThisImg);
        
         ImageIcon logoimgIcon = new ImageIcon(logoImagePath);
        Image lI = logoimgIcon.getImage();
        Image logoDimg = lI.getScaledInstance(30, 30,Image.SCALE_SMOOTH);
        ImageIcon logoImgThisImg = new ImageIcon(logoDimg);
        lblL.setIcon(logoImgThisImg);
        
          ImageIcon bimgIcon = new ImageIcon(bgimagePath);
        Image bI = bimgIcon.getImage();
        Image cDimg = bI.getScaledInstance(200, 800,Image.SCALE_SMOOTH);
        ImageIcon cImgThisImg = new ImageIcon(cDimg);
        lblCB.setIcon(cImgThisImg);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        controlPanel = new javax.swing.JPanel();
        btnMO = new javax.swing.JButton();
        btnME = new javax.swing.JButton();
        btnMU = new javax.swing.JButton();
        btnMEvents = new javax.swing.JButton();
        btnVUR = new javax.swing.JButton();
        btnVP = new javax.swing.JButton();
        lblL = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblA = new javax.swing.JLabel();
        lblCB = new javax.swing.JLabel();
        workArea = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        splitPane.setPreferredSize(new java.awt.Dimension(1300, 800));

        controlPanel.setPreferredSize(new java.awt.Dimension(200, 800));
        controlPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMO.setText("Manage Organisation");
        btnMO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMOActionPerformed(evt);
            }
        });
        controlPanel.add(btnMO, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 160, -1));

        btnME.setText("Manage Employee");
        btnME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMEActionPerformed(evt);
            }
        });
        controlPanel.add(btnME, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 160, -1));

        btnMU.setText("Manage Users");
        btnMU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMUActionPerformed(evt);
            }
        });
        controlPanel.add(btnMU, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 160, -1));

        btnMEvents.setText("Manage Events");
        btnMEvents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMEventsActionPerformed(evt);
            }
        });
        controlPanel.add(btnMEvents, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 160, -1));

        btnVUR.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnVUR.setText("Vaccine Usage Report");
        btnVUR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVURActionPerformed(evt);
            }
        });
        controlPanel.add(btnVUR, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 160, -1));

        btnVP.setText("View Patients");
        btnVP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVPActionPerformed(evt);
            }
        });
        controlPanel.add(btnVP, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 160, -1));

        lblL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLMouseClicked(evt);
            }
        });
        controlPanel.add(lblL, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 610, 50, 40));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel1.setText("CDC Admin");
        controlPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));
        controlPanel.add(lblA, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 90, 70));
        controlPanel.add(lblCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 800));

        splitPane.setLeftComponent(controlPanel);

        workArea.setPreferredSize(new java.awt.Dimension(1100, 800));
        workArea.setLayout(new java.awt.CardLayout());
        splitPane.setRightComponent(workArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1072, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMOActionPerformed
        // TODO add your handling code here:
        
        ManageCdcOrganisation mo = new ManageCdcOrganisation(enterprise.getOrganizationDirectory(), workArea);
        workArea.add("managePatientJPanel", mo);
        CardLayout cardlayout = (CardLayout) workArea.getLayout();
        cardlayout.next(workArea);
//        splitPane.setRightComponent(mo);
    }//GEN-LAST:event_btnMOActionPerformed

    private void btnMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMEActionPerformed
        // TODO add your handling code here:
        ManageCdcEmployee me = new ManageCdcEmployee(enterprise.getOrganizationDirectory(), workArea);
        workArea.add("managePatientJPanel", me);
        CardLayout cardlayout = (CardLayout) workArea.getLayout();
        cardlayout.next(workArea);
//        splitPane.setRightComponent(me);
    }//GEN-LAST:event_btnMEActionPerformed

    private void btnMUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMUActionPerformed
        // TODO add your handling code here:
        ManageCdcUser mu = new ManageCdcUser(enterprise, workArea);
        workArea.add("managePatientJPanel", mu);
        CardLayout cardlayout = (CardLayout) workArea.getLayout();
        cardlayout.next(workArea);
//        splitPane.setRightComponent(mu);
    }//GEN-LAST:event_btnMUActionPerformed

    private void btnMEventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMEventsActionPerformed
        // TODO add your handling code here:
        ManageEventsDirectory mu = new ManageEventsDirectory(enterprise,network,system, workArea);
        workArea.add("managePatientJPanel", mu);
        CardLayout cardlayout = (CardLayout) workArea.getLayout();
        cardlayout.next(workArea);
//        splitPane.setRightComponent(mu);
    }//GEN-LAST:event_btnMEventsActionPerformed

    private void btnVPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVPActionPerformed
        // TODO add your handling code here:
         ViewPatients vp = new ViewPatients(enterprise,network,system, workArea);
        workArea.add("managePatientJPanel", vp);
        CardLayout cardlayout = (CardLayout) workArea.getLayout();
        cardlayout.next(workArea);
//        splitPane.setRightComponent(vp);
    }//GEN-LAST:event_btnVPActionPerformed

    private void btnVURActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVURActionPerformed
        // TODO add your handling code here:
        VaccineUsageReport vp = new VaccineUsageReport(enterprise,network,system,workArea);
        workArea.add("managePatientJPanel", vp);
        CardLayout cardlayout = (CardLayout) workArea.getLayout();
        cardlayout.next(workArea);
//        splitPane.setRightComponent(vp);
    }//GEN-LAST:event_btnVURActionPerformed

    private void lblLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLMouseClicked
        // TODO add your handling code here:
          this.setVisible(false);
        MainLoginJFrame ml = new MainLoginJFrame(system,network);
        ml.setVisible(true); 
    }//GEN-LAST:event_lblLMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(CdcAdminWorkArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(CdcAdminWorkArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(CdcAdminWorkArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(CdcAdminWorkArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new CdcAdminWorkArea().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnME;
    private javax.swing.JButton btnMEvents;
    private javax.swing.JButton btnMO;
    private javax.swing.JButton btnMU;
    private javax.swing.JButton btnVP;
    private javax.swing.JButton btnVUR;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblA;
    private javax.swing.JLabel lblCB;
    private javax.swing.JLabel lblL;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JPanel workArea;
    // End of variables declaration//GEN-END:variables
}
