/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.CDC;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.WorkQueue.CDCReportingWorkRequest;
import Business.WorkQueue.WorkRequest;
import Business.vaccine.Vaccine;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author bhargavi
 */
public class ViewPatients extends javax.swing.JPanel {

    /**
     * Creates new form ViewPatients
     */
    private Enterprise enterprise;
    private Network network;
    private EcoSystem system;
    private ArrayList<Float> ageList;
    private ArrayList<Integer> yearList;
    JPanel workArea;
    public ViewPatients( Enterprise enterprise, Network network, EcoSystem system, JPanel workArea) {
        initComponents();
        this.workArea = workArea;
        this.enterprise = enterprise;
        this.network= network;
        this.system = system;
        ageList = new ArrayList();
        yearList = new ArrayList();
        populateComboBox();
    }
    
    void populateComboBox()
    {
        cbV.removeAllItems();
        
        for (Vaccine vaccine : system.getVaccineDirectory().getVaccineList()) {
            cbV.addItem(vaccine);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbV = new javax.swing.JComboBox();
        btnAge = new javax.swing.JButton();
        btnYear = new javax.swing.JButton();
        btnGender = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txt20 = new javax.swing.JTextField();
        txt21 = new javax.swing.JTextField();
        txt22 = new javax.swing.JTextField();
        txtChange = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtInfant = new javax.swing.JTextField();
        txtTwo = new javax.swing.JTextField();
        txtSix = new javax.swing.JTextField();
        txtTen = new javax.swing.JTextField();
        txtTwenty = new javax.swing.JTextField();
        txtGT = new javax.swing.JTextField();
        txtTot = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtM = new javax.swing.JTextField();
        txtF = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(800, 800));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setText("Report");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, -1, -1));

        jLabel2.setText("Select Vaccine :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, -1, -1));

        cbV.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbVActionPerformed(evt);
            }
        });
        add(cbV, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 66, -1, -1));

        btnAge.setBackground(new java.awt.Color(255, 244, 244));
        btnAge.setText("Get Report By Age");
        btnAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgeActionPerformed(evt);
            }
        });
        add(btnAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 128, -1, -1));

        btnYear.setBackground(new java.awt.Color(255, 244, 244));
        btnYear.setText("Get Report by year");
        btnYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYearActionPerformed(evt);
            }
        });
        add(btnYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 128, -1, -1));

        btnGender.setBackground(new java.awt.Color(255, 244, 244));
        btnGender.setText("Get Report by Gender");
        btnGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenderActionPerformed(evt);
            }
        });
        add(btnGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel3.setText("Vaccine doses per age");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel4.setText("Vaccine Doses per year");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 188, -1, -1));

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel5.setText("Vaccine doses by gender");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(629, 188, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 244, 244));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel15.setText("Year");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 27, -1, -1));

        jLabel16.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel16.setText("No of Cases");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 27, -1, -1));

        jLabel17.setText("2020");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 78, -1, -1));

        jLabel18.setText("2021");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 122, -1, -1));

        jLabel19.setText("2022");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 169, -1, -1));

        jLabel20.setText("% change");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 248, -1, -1));

        txt20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt20ActionPerformed(evt);
            }
        });
        jPanel1.add(txt20, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 75, 82, -1));

        txt21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt21ActionPerformed(evt);
            }
        });
        jPanel1.add(txt21, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 119, 82, -1));

        txt22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt22ActionPerformed(evt);
            }
        });
        jPanel1.add(txt22, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 166, 82, -1));

        txtChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChangeActionPerformed(evt);
            }
        });
        jPanel1.add(txtChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 245, 82, -1));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/image.jpg"))); // NOI18N
        jLabel27.setText("jLabel27");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 390));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 260, 390));

        jPanel2.setBackground(new java.awt.Color(255, 244, 244));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel6.setText("Age Group");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 23, -1, -1));

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel7.setText("Frequency");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 23, -1, -1));

        jLabel8.setText("< 1 year :");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 71, -1, -1));

        jLabel9.setText("2-5 years :");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 112, -1, -1));

        jLabel10.setText("6-9 years :");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 153, -1, -1));

        jLabel11.setText("10-20 years :");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 194, -1, -1));

        jLabel12.setText("20-30 years :");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 235, -1, -1));

        jLabel13.setText(">30 years :");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 276, -1, -1));

        jLabel14.setText("Total :");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 317, -1, -1));

        txtInfant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInfantActionPerformed(evt);
            }
        });
        jPanel2.add(txtInfant, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 68, 78, -1));
        jPanel2.add(txtTwo, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 109, 78, -1));
        jPanel2.add(txtSix, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 150, 78, -1));
        jPanel2.add(txtTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 191, 78, -1));
        jPanel2.add(txtTwenty, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 232, 78, -1));
        jPanel2.add(txtGT, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 273, 78, -1));
        jPanel2.add(txtTot, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 314, 78, -1));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/image.jpg"))); // NOI18N
        jLabel28.setText("jLabel28");
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 390));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 290, 380));

        jPanel3.setBackground(new java.awt.Color(255, 244, 244));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel21.setText("Gender");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 26, -1, -1));

        jLabel22.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel22.setText("No of Cases");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 26, -1, -1));

        jLabel23.setText("Female :");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 134, -1, -1));

        jLabel24.setText("Male :");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 89, -1, -1));

        txtM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMActionPerformed(evt);
            }
        });
        jPanel3.add(txtM, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 86, 82, -1));

        txtF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFActionPerformed(evt);
            }
        });
        jPanel3.add(txtF, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 131, 82, -1));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/image.jpg"))); // NOI18N
        jLabel26.setText("jLabel26");
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 390));

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 220, 250, 390));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/image.jpg"))); // NOI18N
        jLabel25.setText("jLabel25");
        jLabel25.setPreferredSize(new java.awt.Dimension(800, 800));
        add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 800));
    }// </editor-fold>//GEN-END:initComponents

    private void txtInfantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInfantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInfantActionPerformed

    private void txt20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt20ActionPerformed

    private void txt21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt21ActionPerformed

    private void txt22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt22ActionPerformed

    private void txtChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChangeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChangeActionPerformed

    private void txtMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMActionPerformed

    private void txtFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFActionPerformed

    private void btnAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgeActionPerformed
        // TODO add your handling code here:
        
           for(WorkRequest wr : network.getWorkQueue().getWorkRequestList())  
       {
           if(wr instanceof CDCReportingWorkRequest){               
               if(cbV.getSelectedItem().equals(wr.getVaccine()))
               {
                   ageList.add(Float.parseFloat((((CDCReportingWorkRequest) wr).getPatient().getAge())));
                   //ageList.add(Float.parseFloat(((CDCReportingWorkRequest) wr).getPatient().getAge()));
               }                
           }
       }
        System.out.println(ageList);
        
       int sixthval=0,tot=0,fifthval=0,newborn = 0, secondval = 0, thirdval =0, forthval=0;
        
        for(Float age : ageList)
        {   
            if(age<1.0)
            {
                newborn++;
            }
            if(age>2.0 && age<5.0)
            {
                secondval++;
            }
            if(age>6.0 && age<9.0)
            {
                thirdval++;
            }
            if(age>10.0 && age<20.0)
            {
                forthval++;
            }
            if(age>21.0 && age<30.0)
            {
                fifthval++;
            }
            if(age>30.0)
            {
                sixthval++;
            }
        }
        ageList.clear();
        
        tot= newborn+secondval+thirdval+forthval+fifthval+sixthval;
        txtInfant.setText(String.valueOf(newborn));
        txtTwo.setText(String.valueOf(secondval));
        txtSix.setText(String.valueOf(thirdval));
        txtTen.setText(String.valueOf(forthval));
        txtTwenty.setText(String.valueOf(fifthval));
        txtGT.setText(String.valueOf(sixthval));
        txtTot.setText(String.valueOf(tot));
        
//        txtNewBorn1.setText(String.valueOf((newborn*100)/tot));
//        txtSecondVal1.setText(String.valueOf((secondval*100)/tot));
//        txtThirdVal1.setText(String.valueOf((thirdval*100)/tot));
//        txtForthVal1.setText(String.valueOf((forthval*100)/tot));
        
        
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        dataset.setValue(newborn, "", "<1 year");
        dataset.setValue(secondval, "", "2-5 years");
        dataset.setValue(thirdval, "", "6-9 years");
        dataset.setValue(forthval, "", "10-20 years");
        dataset.setValue(forthval, "", "21-30 years");
        dataset.setValue(forthval, "", ">30 years");
        
        JFreeChart chart = ChartFactory.createBarChart("Frequency of vaccines according to age groups", "", "", dataset, PlotOrientation.VERTICAL, false, true, false);
        CategoryPlot catPlot = chart.getCategoryPlot();
        catPlot.setRangeGridlinePaint(Color.BLACK);
        
        ChartFrame frame = new ChartFrame("Bar Chart for Age groups",chart);
        frame.setVisible(true);
        frame.setSize(650,350);
    }//GEN-LAST:event_btnAgeActionPerformed

    private void cbVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbVActionPerformed

    private void btnYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYearActionPerformed
        // TODO add your handling code here:
         Calendar cal = Calendar.getInstance();
        for(WorkRequest wr : network.getWorkQueue().getWorkRequestList())  
        {
           if(wr instanceof CDCReportingWorkRequest){
               
               if(cbV.getSelectedItem().equals(wr.getVaccine()))
               {
                   
                   Date d = ((CDCReportingWorkRequest) wr).getPatient().getDate();
                   cal.setTime(d);
                   int year = cal.get(Calendar.YEAR);
                   yearList.add(year);
               }                
           }
         }
        
       int firstyear=0, secondyear=0, thirdyear=0; 
        
       for(Integer year: yearList)
       {
           if(String.valueOf(year).equals("2017"))
           {
              firstyear++;
           }
           if(String.valueOf(year).equals("2016"))
           {
              secondyear++;
           }
           if(String.valueOf(year).equals("2015"))
           {
              thirdyear++;
           }
           
       }
       yearList.clear();
        
       txt20.setText(String.valueOf(firstyear));
       txt21.setText(String.valueOf(secondyear));
       txt22.setText(String.valueOf(thirdyear));
       
       float perIncrease=0;
       float perDecrease=0;
       
       if(firstyear-thirdyear>0)
       {
           txtChange.setOpaque(true);
           txtChange.setBackground(Color.red);
           perIncrease = (((firstyear-thirdyear)*100)/thirdyear);
           txtChange.setText(String.valueOf(perIncrease));
       }
       if(firstyear-thirdyear<0)
       {
           txtChange.setOpaque(true);
           txtChange.setBackground(Color.green);
           perDecrease = (((thirdyear-firstyear)*100)/thirdyear);
           txtChange.setText(String.valueOf(perDecrease));
       }
       
      DefaultCategoryDataset dataset = new DefaultCategoryDataset( );
      dataset.addValue( thirdyear , "" , "2015" );
      dataset.addValue( secondyear , "" , "2016" );
      dataset.addValue( firstyear , "" ,  "2017" );
      
       JFreeChart chart = ChartFactory.createLineChart("Vaccine doses per year", "", "", dataset, PlotOrientation.VERTICAL, false, true, false);
       CategoryPlot catPlot = chart.getCategoryPlot();
       catPlot.setRangeGridlinePaint(Color.BLACK);
        
       ChartFrame frame = new ChartFrame("line Chart for Vaccine doses",chart);
       frame.setVisible(true);
       frame.setSize(450,350);
    }//GEN-LAST:event_btnYearActionPerformed

    private void btnGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenderActionPerformed
        // TODO add your handling code here:
        
        int maleCount=0, femaleCount=0;

        for(WorkRequest wrkReq : network.getWorkQueue().getWorkRequestList())
        {
            if(wrkReq instanceof CDCReportingWorkRequest)
            {
                if(cbV.getSelectedItem().equals(wrkReq.getVaccine()))
                {
                    if(((CDCReportingWorkRequest) wrkReq).getPatient().getGender().equals("Male"))
                    {
                        maleCount++;
                    }
                    else if(((CDCReportingWorkRequest) wrkReq).getPatient().getGender().equals("Female"))
                    {
                        femaleCount++;
                    }
                }
            }
        }
        txtM.setText(String.valueOf(maleCount));
        txtF.setText(String.valueOf(femaleCount));
    }//GEN-LAST:event_btnGenderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAge;
    private javax.swing.JButton btnGender;
    private javax.swing.JButton btnYear;
    private javax.swing.JComboBox cbV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txt20;
    private javax.swing.JTextField txt21;
    private javax.swing.JTextField txt22;
    private javax.swing.JTextField txtChange;
    private javax.swing.JTextField txtF;
    private javax.swing.JTextField txtGT;
    private javax.swing.JTextField txtInfant;
    private javax.swing.JTextField txtM;
    private javax.swing.JTextField txtSix;
    private javax.swing.JTextField txtTen;
    private javax.swing.JTextField txtTot;
    private javax.swing.JTextField txtTwenty;
    private javax.swing.JTextField txtTwo;
    // End of variables declaration//GEN-END:variables
}
